/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.LaberintoController;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import views.tables.ModeloTablaLaberinto;

public class FrmLaberinto extends javax.swing.JDialog {
    
    private ModeloTablaLaberinto ml;
    private LaberintoController laberintoController;


    /**
     * Creates new form FrmLaberinto
     */
    public FrmLaberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
         laberintoController = new LaberintoController(); 
         ml = new ModeloTablaLaberinto(laberintoController); 
         initComponents(); cargar_tabla();
         ajustarColumnas();
         pintarLaberinto();
        
    }
    private void cargar_tabla() {
        Integer dimen = (Integer) spndimensiones.getValue();
        if (dimen != null) {
            ml.actualizarLaberinto(dimen, dimen);
            tbltabla.setModel(ml);
        }

    }
    private void ajustarColumnas() {
        if (tbltabla.getColumnCount() > 0) {
            int anchoColumna = 25;
            for (int i = 0; i < tbltabla.getColumnCount(); i++) {
                tbltabla.getColumnModel().getColumn(i).setPreferredWidth(anchoColumna);
                tbltabla.getColumnModel().getColumn(i).setMaxWidth(anchoColumna);
                tbltabla.getColumnModel().getColumn(i).setMinWidth(anchoColumna);
            }
        }

    }
    private void dimenciones() {
        cargar_tabla();
        ajustarColumnas();
        pintarLaberinto();

    }
    private void pintarLaberinto() {
        if (tbltabla.getColumnCount() > 0) {
            tbltabla.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int column) {
                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    if (value != null) {

                        switch (value.toString()) {
                            case "1":
                                c.setBackground(Color.BLACK);
                                c.setForeground(Color.BLACK);
                                break;
                            case "0":
                                c.setBackground(Color.LIGHT_GRAY);
                                c.setForeground(Color.LIGHT_GRAY );
                                break;

                            default:
                                c.setBackground(Color.GRAY);
                                c.setForeground(Color.GRAY);
                                break;
                        }
                    } else {
                        c.setBackground(Color.GRAY);
                        c.setForeground(Color.GRAY);
                    }
                    return c;
                }
            });

            tbltabla.setRowHeight(20);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spndimensiones = new javax.swing.JSpinner();
        btnaceptar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LABERINTO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 20, 110, 25);

        jPanel2.setLayout(null);

        jLabel2.setText("ELIJA UNA DIMENSION");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 20, 140, 16);

        spndimensiones.setModel(new javax.swing.SpinnerNumberModel(5, 3, 100, 1));
        jPanel2.add(spndimensiones);
        spndimensiones.setBounds(200, 20, 64, 22);

        btnaceptar.setText("ACEPTAR");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnaceptar);
        btnaceptar.setBounds(300, 20, 90, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 50, 410, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        jPanel3.setLayout(null);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 450, 330);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 110, 450, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 420);

        setSize(new java.awt.Dimension(477, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
dimenciones();        
// TODO add your handling code here:
    }//GEN-LAST:event_btnaceptarActionPerformed
  
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLaberinto dialog = new FrmLaberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spndimensiones;
    private javax.swing.JTable tbltabla;
    // End of variables declaration//GEN-END:variables
}
